########################################
###    CENM configuration options    ###
########################################

# Display more messages while executing Kubernetes deployment
bashDebug: false

# Docker images to use by the Auth Service Helm chart
authImage:
  repository: corda/enterprise-auth
  tag: 1.0.2-zulu-openjdk8u242
  pullPolicy: Always

# Configuration for database
database:
  driverClassName: "org.h2.Driver"
  jdbcDriver: ""
  url: "jdbc:h2:file:./h2/auth-persistence;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;WRITE_DELAY=0;AUTO_SERVER_PORT=0"
  user: "testuser"
  password: "password"
  runMigration: true

# Volume size for etc/ directory
volumeSizeAuthEtc: 1Gi

# Volume size for h2/ directory
volumeSizeAuthH2: 5Gi

# Volume size for logs/ directory
volumeSizeAuthLogs: 5Gi

# Sleep time (in seconds) after an error occured
sleepTimeAfterError: 300

# Enable container displaying live logs
logsContainersEnabled: true

########################################
###   Kubernetes related settings    ###
########################################

# Name of Kubernetes secret storing credentials to Docker registry
imagePullSecrets:
  - name: cenm-registry

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8081

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
  #   cpu: 100m
    memory: 2Gi
  requests:
  #   cpu: 100m
    memory: 2Gi

nodeSelector: {}

tolerations: []

affinity: {}

## Liveness and readiness probe values
## Ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes
##
livenessProbe:
  enabled: false
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  enabled: false
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

storageClass: cenm
